language: ruby
services:
  - redis
addons:
  postgresql: 9.3
rvm:
  - jruby-19mode
  - 2.0.0
  - 2.1.2
jdk: oraclejdk7
matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.1.2
before_script:
  # create 'logs' table matching 'travis-logs'
  - ./set_up_travis_logs.sh
  # set up travis_test DB
  - redis-cli config set save ""
  - 'RAILS_ENV=test bundle exec rake db:create db:structure:load --trace'
  # replace 'logs' table in travis_test DB with that in travis_logs_test
  - psql -c "DROP TABLE IF EXISTS logs CASCADE" -U postgres travis_test
  - pg_dump -t logs travis_logs_test | psql -U postgres travis_test

script:
  - ./build.sh
notifications:
  irc: irc.freenode.org#travis
  campfire:
    rooms:
      - secure: "FYd2nZjSOnzG0PoCfQ4mHYgjdj6W1C8jLoM6j+OsiLFDo37ShIwuMDjXkBNurUYY1ZyGLPZFngiC4QDZCw1RwefqMukjMqMG4BMt5SV3PNnodrJqLYcT6UfbzwDx8KaoiqClwBHGChzKj+2LgGSwhXxDwO7MqX4snJHTOLAwNy4="
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (details: %{build_url}, changes: %{compare_url})'
