language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
jdk: openjdk6
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: jruby-head
  include:
    - rvm: jruby-head
      env: JRUBY_OPTS=--1.9
    - rvm: jruby-head
      env: JRUBY_OPTS=--1.8
before_script:
  - 'RAILS_ENV=test rake db:create db:schema:load --trace'
notifications:
  irc: "irc.freenode.org#travis"
