rvm:
  - 1.9.2
  - jruby
before_script:
  - 'psql -c "create database travis_test;" -U postgres'
  - 'RAILS_ENV=test bundle install rake db:schema:load'
notifications:
  irc: "irc.freenode.org#travis"
