language: ruby
services:
  - redis
addons:
  postgresql: 9.3
rvm:
  - jruby-19mode
  - 2.0.0
  - 2.1.2
jdk: oraclejdk7
matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.1.2
before_script:
  - OLD_BUNDLE_GEMFILE=$BUNDLE_GEMFILE
  - pushd $HOME
  - git clone --depth=1 https://github.com/travis-ci/travis-logs.git
  - cd travis-logs
  - rvm use jruby-19mode
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - bundle install
  - psql -c "CREATE DATABASE travis_logs_test;" -U postgres
  - cp $TRAVIS_BUILD_DIR/config/database.yml config/travis.yml
  - bundle exec rake db:migrate
  - popd
  - rvm use $TRAVIS_RUBY_VERSION
  - export BUNDLE_GEMFILE=$OLD_BUNDLE_GEMFILE
  - sudo service mysql stop
  - redis-cli config set save ""
  - 'RAILS_ENV=test bundle exec rake db:create db:structure:load --trace'
  - psql -c "DROP TABLE IF EXISTS logs CASCADE" -U postgres travis_test
  - pg_dump -t logs travis_logs_test | psql -U postgres travis_test

script:
  - ./build.sh
notifications:
  irc: irc.freenode.org#travis
  campfire:
    rooms:
      - secure: "FYd2nZjSOnzG0PoCfQ4mHYgjdj6W1C8jLoM6j+OsiLFDo37ShIwuMDjXkBNurUYY1ZyGLPZFngiC4QDZCw1RwefqMukjMqMG4BMt5SV3PNnodrJqLYcT6UfbzwDx8KaoiqClwBHGChzKj+2LgGSwhXxDwO7MqX4snJHTOLAwNy4="
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (details: %{build_url}, changes: %{compare_url})'
