language: ruby
rvm:
  - 1.9.2
  - jruby-18mode
  - jruby-19mode
  - jruby-head
before_script:
  - 'RAILS_ENV=test bundle exec rake db:create db:schema:load --trace'
notifications:
  irc: "irc.freenode.org#travis"
